### ISSUE TITLE
instead of enable/disable buttons, use a toggle control

### ISSUE THREAD

**Issue by jrwren** [jrwren/etv#6]
![image](https://user-images.githubusercontent.com/106443/96353481-8c501a80-109a-11eb-890e-7c1d7ecc7b5d.png)
and
![image](https://user-images.githubusercontent.com/106443/96353484-94a85580-109a-11eb-9304-c054eff6ae26.png)

**Comment by SolKuczala** [comment]
hi! I'll see if I can help :)

**Comment by SolKuczala** [comment]
I was able to change the buttons for switches sliders, and now I'm working on the logic for them because need a different "onclick" manage with JS according to your function which is sending a path to the server. Is ok with that?

On other hand, I need to point out that the variables on the beginning of the script should be const as that information doesn't change/shouldn't change (the element you're taking).

**Comment by jrwren** [comment]
Yes, as long as a request is sent to the server on toggle event and it is correct for enable/disable, then it is OK.

If I have vars or lets that would be better off consts, yes please change them.

**Comment by SolKuczala** [comment]
Q: etv has no "disable" option, is because of a particular reason? Because I think it'll need some other element that signifies that it starts until shut down the server or refresh the webpage

**Comment by jrwren** [comment]
Not really, in fact, there is another issue to make it work more like the others.

**Comment by jrwren** [comment]
Looks great:
![Screen Shot 2020-10-20 at 5 57 06 PM](https://user-images.githubusercontent.com/106443/96648727-c8cf8080-12fd-11eb-8e0a-aefadd679411.png)
